{% set name = "pygtrie" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 926f92b7fc5aa4f5f38c9227b1925603cd18891c45cabd01ae76b22d2446eabb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - packaging
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pygtrie

about:
  home: https://github.com/google/pygtrie
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python library implementing a trie data structure.
  doc_url: https://pygtrie.readthedocs.io/en/latest/
  dev_url: https://github.com/google/pygtrie

extra:
  recipe-maintainers:
    - Suor
    - shcheklein
